-- MySQL Script generated by MySQL Workbench
-- Sat Oct  6 13:36:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema finaldb20
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema finaldb20
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finaldb20` DEFAULT CHARACTER SET utf8 ;
USE `finaldb20` ;

-- -----------------------------------------------------
-- Table `finaldb20`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb20`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `login` VARCHAR(80) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `rating` INT NULL,
  `banned` INT UNSIGNED NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(1025) NULL,
  `phone` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `age` INT UNSIGNED NULL,
  `favoritehero` VARCHAR(80) NULL,
  `nickname` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb20`.`Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb20`.`Hero` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rating` INT NOT NULL,
  `description` BLOB NULL,
  `type` VARCHAR(45) NOT NULL,
  `deleted` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb20`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb20`.`Comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(450) NOT NULL,
  `deleted` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `hero_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `hero_id`),
  INDEX `fk_Comment_User1_idx` (`user_id` ASC),
  INDEX `fk_Comment_Hero1_idx` (`hero_id` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `finaldb20`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Hero1`
    FOREIGN KEY (`hero_id`)
    REFERENCES `finaldb20`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb20`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb20`.`image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(1025) NULL,
  `Hero_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `Hero_id`),
  INDEX `fk_image_Hero_idx` (`Hero_id` ASC),
  CONSTRAINT `fk_image_Hero`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `finaldb20`.`Hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
